some addition in requirements section

diff --git a/phish b/phish
--- a/phish
+++ b/phish
@@ -9,12 +9,29 @@ distro=$(cd $HOME && pwd)
 case ${OS} in
 Android)
 	if ! hash jq > /dev/null 2>&1; then
+	printf "\033[32m[\033[31m!\033[32m]\033[31mjq not found! \033[34mINSTALLING.......\033[00m\n"
 	apt install jq -y > /dev/null 2>&1
+	fi
+	if ! hash pv > /dev/null 2>&1; then
+	printf "\n\033[32m[\033[31m!\033[32m]\033[31mpv not found! \033[34mINSTALLING.......\033[00m\n"
+	apt install pv -y > /dev/null 2>&1
+	fi
+	if [[ ! -f "$PREFIX/bin/lolcat" ]]; then
+	printf "\n\033[32m[\033[31m!\033[32m]\033[31mlolcat not found! \033[34mINSTALLING.......\033[00m\n"
+	apt install python -y && pip install lolcat > /dev/null 2>&1
 	fi
 ;;
 GNU/Linux)
 	if ! hash jq > /dev/null 2>&1; then
         sudo apt install jq -y > /dev/null 2>&1
+        fi
+	if ! hash pv > /dev/null 2>&1; then
+        printf "\n\033[32m[\033[31m!\033[32m]\033[31mpv not found! \033[34mINSTALLING.......\033[00m\n"
+        sudo apt install pv -y > /dev/null 2>&1
+        fi
+        if [[ ! -f "$PREFIX/bin/lolcat" ]]; then
+        printf "\n\033[32m[\033[31m!\033[32m]\033[31mlolcat not found! \033[34mINSTALLING.......\033[00m\n"
+        sudo apt install python -y && pip install lolcat > /dev/null 2>&1
         fi
 ;;
 esac
